/* The following code was generated by JFlex 1.7.0 */

package klx.parser;
import java.io.FileReader;
import java.io.StringReader;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import klx.Token;
import klx.Token.EType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>klx.flex</tt>
 */
public class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARLITERAL = 4;
  public static final int REGEX = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\101\1\102\1\1\22\0\1\3\1\70\1\25"+
    "\2\0\1\100\1\74\1\15\1\56\1\57\1\5\1\76\1\64\1\13"+
    "\1\11\1\4\1\10\1\17\2\103\4\14\2\7\1\73\1\63\1\67"+
    "\1\65\1\66\1\72\1\0\1\24\1\16\1\24\1\23\1\12\1\24"+
    "\1\6\1\22\6\6\1\21\13\6\1\61\1\26\1\62\1\77\1\20"+
    "\1\0\1\30\1\33\1\36\1\32\1\41\1\42\1\51\1\55\1\43"+
    "\1\6\1\50\1\35\1\46\1\31\1\34\1\47\1\6\1\45\1\37"+
    "\1\40\1\53\1\52\1\54\1\44\2\6\1\60\1\75\1\27\1\71"+
    "\6\0\1\101\u1fa2\0\1\101\1\101\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\1\12\1\13\17\5\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\40\1\41\2\1\2\42\1\1\1\37\2\43"+
    "\1\1\1\44\1\45\1\0\1\46\1\47\1\50\2\0"+
    "\1\50\1\51\1\52\1\53\4\0\5\5\1\54\12\5"+
    "\1\55\7\5\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\0"+
    "\1\73\1\74\2\75\1\76\1\77\1\100\1\101\1\102"+
    "\1\103\1\104\1\105\1\106\12\74\1\107\2\45\1\0"+
    "\1\50\1\0\4\110\1\111\1\112\1\113\1\114\11\5"+
    "\1\115\1\5\1\116\5\5\1\117\2\5\1\120\1\121"+
    "\1\122\1\123\1\75\1\0\1\124\1\0\1\125\1\126"+
    "\1\127\1\130\1\131\1\132\1\133\1\134\1\135\3\5"+
    "\1\136\1\137\1\140\14\5\1\141\1\142\1\143\2\5"+
    "\1\144\1\145\10\5\1\146\1\147\2\5\1\150\4\5"+
    "\1\151\1\152\1\153\2\5\1\154\1\5\1\155\3\5"+
    "\1\156\1\5\1\157\1\160";

  private static int [] zzUnpackAction() {
    int [] result = new int[248];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\210\0\314\0\u0110\0\u0110\0\u0154\0\u0198"+
    "\0\u01dc\0\u0220\0\u0264\0\u02a8\0\u02ec\0\u0330\0\u0110\0\u0110"+
    "\0\u0374\0\u03b8\0\u03fc\0\u0440\0\u0484\0\u04c8\0\u050c\0\u0550"+
    "\0\u0594\0\u05d8\0\u061c\0\u0660\0\u06a4\0\u06e8\0\u072c\0\u0110"+
    "\0\u0110\0\u0110\0\u0110\0\u0110\0\u0110\0\u0110\0\u0770\0\u07b4"+
    "\0\u07f8\0\u083c\0\u0110\0\u0110\0\u0110\0\u0880\0\u08c4\0\u0908"+
    "\0\u094c\0\u0990\0\u09d4\0\u0a18\0\u0110\0\u0110\0\u0a5c\0\u0aa0"+
    "\0\u0ae4\0\u0110\0\u0b28\0\u0b6c\0\u0bb0\0\u0110\0\u0bf4\0\u0110"+
    "\0\u0c38\0\u0c7c\0\u0110\0\u0110\0\u0cc0\0\u0d04\0\u0330\0\u0264"+
    "\0\u0110\0\u0110\0\u0110\0\u0d48\0\u0d8c\0\u0dd0\0\u0e14\0\u0e58"+
    "\0\u0e9c\0\u0ee0\0\u0f24\0\u0f68\0\u01dc\0\u0fac\0\u0ff0\0\u1034"+
    "\0\u1078\0\u10bc\0\u1100\0\u1144\0\u1188\0\u11cc\0\u1210\0\u01dc"+
    "\0\u1254\0\u1298\0\u12dc\0\u1320\0\u1364\0\u13a8\0\u13ec\0\u0110"+
    "\0\u0110\0\u1430\0\u0110\0\u1474\0\u0110\0\u0110\0\u0110\0\u0110"+
    "\0\u0110\0\u0110\0\u0110\0\u0110\0\u14b8\0\u0110\0\u0110\0\u14fc"+
    "\0\u1540\0\u0110\0\u0110\0\u0110\0\u0110\0\u0110\0\u0110\0\u0110"+
    "\0\u0110\0\u0110\0\u1584\0\u15c8\0\u160c\0\u1650\0\u1694\0\u16d8"+
    "\0\u171c\0\u1760\0\u17a4\0\u17e8\0\u0110\0\u182c\0\u0110\0\u1870"+
    "\0\u18b4\0\u18b4\0\u18f8\0\u193c\0\u1980\0\u19c4\0\u01dc\0\u01dc"+
    "\0\u01dc\0\u01dc\0\u1a08\0\u1a4c\0\u1a90\0\u1ad4\0\u1b18\0\u1b5c"+
    "\0\u1ba0\0\u1be4\0\u1c28\0\u01dc\0\u1c6c\0\u1cb0\0\u1cf4\0\u1d38"+
    "\0\u1d7c\0\u1dc0\0\u1e04\0\u01dc\0\u1e48\0\u1e8c\0\u0110\0\u1ed0"+
    "\0\u0110\0\u0110\0\u0110\0\u15c8\0\u0110\0\u1f14\0\u0110\0\u0110"+
    "\0\u0110\0\u0110\0\u0110\0\u0110\0\u0110\0\u0110\0\u01dc\0\u1f58"+
    "\0\u1f9c\0\u1fe0\0\u01dc\0\u01dc\0\u01dc\0\u2024\0\u2068\0\u20ac"+
    "\0\u20f0\0\u2134\0\u2178\0\u21bc\0\u2200\0\u2244\0\u2288\0\u22cc"+
    "\0\u2310\0\u0110\0\u01dc\0\u01dc\0\u2354\0\u2398\0\u01dc\0\u01dc"+
    "\0\u23dc\0\u2420\0\u2464\0\u24a8\0\u24ec\0\u2530\0\u2574\0\u25b8"+
    "\0\u01dc\0\u01dc\0\u25fc\0\u2640\0\u01dc\0\u2684\0\u26c8\0\u270c"+
    "\0\u2750\0\u01dc\0\u01dc\0\u01dc\0\u2794\0\u27d8\0\u01dc\0\u281c"+
    "\0\u01dc\0\u2860\0\u28a4\0\u28e8\0\u01dc\0\u292c\0\u01dc\0\u01dc";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[248];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\3\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\11\1\15\1\12\1\16\1\11\1\12\5\11\1\17"+
    "\1\5\1\20\1\21\1\22\1\23\1\24\1\25\1\11"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\3\11\1\34"+
    "\2\11\1\35\1\36\1\37\1\11\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\5\1\6\1\12\1\63\1\64\1\65\22\63\1\66"+
    "\1\67\55\63\1\70\1\71\1\72\12\70\1\5\10\70"+
    "\1\73\55\70\1\74\1\75\1\76\23\74\1\77\1\100"+
    "\54\74\110\0\1\101\1\102\57\0\1\103\103\0\1\104"+
    "\24\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\26\11\25\0\1\11\7\0\2\12\1\105\1\106"+
    "\1\0\1\12\1\107\1\0\1\12\21\0\1\106\41\0"+
    "\1\12\7\0\2\110\1\105\1\106\1\0\1\110\2\0"+
    "\1\110\21\0\1\106\41\0\1\110\7\0\2\105\1\111"+
    "\2\0\1\105\2\0\1\105\63\0\1\105\13\0\1\112"+
    "\51\0\1\113\34\0\1\114\2\0\1\115\1\116\1\117"+
    "\6\0\1\117\1\114\1\115\20\0\1\116\34\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\1\11"+
    "\1\120\24\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\4\11\1\121\6\11"+
    "\1\122\12\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\11\11\1\123\14\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\4\11\1\124\21\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\15\11\1\125\10\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\4\11"+
    "\1\126\1\127\20\11\25\0\1\11\6\0\3\11\1\0"+
    "\1\11\1\0\1\11\1\0\7\11\3\0\10\11\1\130"+
    "\15\11\25\0\1\11\6\0\3\11\1\0\1\11\1\0"+
    "\1\11\1\0\7\11\3\0\15\11\1\131\10\11\25\0"+
    "\1\11\6\0\3\11\1\0\1\11\1\0\1\11\1\0"+
    "\7\11\3\0\5\11\1\132\6\11\1\133\11\11\25\0"+
    "\1\11\6\0\3\11\1\0\1\11\1\0\1\11\1\0"+
    "\7\11\3\0\1\134\3\11\1\135\1\136\20\11\25\0"+
    "\1\11\6\0\3\11\1\0\1\11\1\0\1\11\1\0"+
    "\7\11\3\0\1\11\1\137\10\11\1\140\3\11\1\141"+
    "\7\11\25\0\1\11\6\0\3\11\1\0\1\11\1\0"+
    "\1\11\1\0\7\11\3\0\1\142\14\11\1\143\5\11"+
    "\1\144\2\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\1\145\25\11\25\0"+
    "\1\11\6\0\3\11\1\0\1\11\1\0\1\11\1\0"+
    "\7\11\3\0\1\11\1\146\24\11\25\0\1\11\6\0"+
    "\3\11\1\0\1\11\1\0\1\11\1\0\7\11\3\0"+
    "\25\11\1\147\25\0\1\11\65\0\1\150\103\0\1\151"+
    "\1\152\102\0\1\153\1\0\1\154\101\0\1\155\103\0"+
    "\1\156\6\0\1\157\74\0\1\160\7\0\1\161\73\0"+
    "\1\162\10\0\1\163\72\0\1\164\63\0\1\165\17\0"+
    "\1\166\16\0\1\63\2\0\22\63\2\0\55\63\2\0"+
    "\1\65\101\0\1\167\2\0\5\167\1\170\3\167\1\171"+
    "\1\172\1\167\1\170\5\167\1\173\1\174\2\167\1\175"+
    "\1\167\1\176\4\167\1\177\1\167\1\200\2\167\1\201"+
    "\33\167\2\0\1\170\15\0\1\202\70\0\1\72\101\0"+
    "\1\167\2\0\5\167\1\203\3\167\1\204\1\205\1\167"+
    "\1\203\5\167\1\206\1\207\2\167\1\210\1\167\1\211"+
    "\4\167\1\212\1\167\1\213\2\167\1\214\33\167\2\0"+
    "\1\203\1\74\2\0\23\74\2\0\54\74\2\0\1\76"+
    "\101\0\1\167\2\0\24\167\1\215\51\167\2\0\1\167"+
    "\1\101\1\216\1\217\101\101\5\102\1\220\76\102\7\0"+
    "\2\105\1\0\1\106\1\0\1\105\2\0\1\105\21\0"+
    "\1\106\41\0\1\105\7\0\2\221\2\0\1\222\1\221"+
    "\2\0\1\221\56\0\1\222\4\0\1\221\10\0\1\223"+
    "\6\0\1\223\74\0\1\224\3\0\1\224\2\0\1\224"+
    "\63\0\1\224\7\0\2\225\1\0\1\225\1\0\1\225"+
    "\1\0\2\225\3\0\2\225\3\0\1\225\1\0\2\225"+
    "\2\0\1\225\2\0\2\225\40\0\1\225\7\0\2\226"+
    "\3\0\1\226\2\0\1\226\63\0\1\226\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\2\11"+
    "\1\227\23\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\10\11\1\230\15\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\5\11\1\231\20\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\12\11\1\232\13\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\4\11"+
    "\1\233\21\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\1\11\1\234\24\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\1\235\25\11\25\0\1\11\6\0"+
    "\3\11\1\0\1\11\1\0\1\11\1\0\7\11\3\0"+
    "\1\236\25\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\23\11\1\237\2\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\7\11\1\240\3\11\1\241\12\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\10\11\1\242\15\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\5\11\1\243\20\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\15\11"+
    "\1\244\10\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\4\11\1\245\21\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\10\11\1\246\15\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\17\11\1\247\6\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\6\11"+
    "\1\250\17\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\4\11\1\251\6\11"+
    "\1\252\12\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\3\11\1\253\22\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\15\11\1\254\10\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\5\11\1\255\20\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\13\11"+
    "\1\256\12\11\25\0\1\11\65\0\1\257\1\260\102\0"+
    "\1\261\76\0\1\262\33\0\1\171\3\0\1\171\2\0"+
    "\1\171\63\0\1\171\10\0\1\263\3\0\1\263\2\0"+
    "\1\263\63\0\1\263\10\0\1\264\3\0\1\264\1\265"+
    "\1\0\1\264\63\0\1\264\10\0\1\266\3\0\1\266"+
    "\1\265\1\0\1\266\63\0\1\266\15\0\1\267\103\0"+
    "\1\270\103\0\1\271\103\0\1\272\103\0\1\273\103\0"+
    "\1\274\103\0\1\275\103\0\1\276\70\0\1\217\101\0"+
    "\4\102\1\217\1\220\76\102\7\0\2\221\3\0\1\221"+
    "\2\0\1\221\63\0\1\221\10\0\1\223\6\0\2\223"+
    "\73\0\1\224\3\0\1\224\2\0\2\224\62\0\1\224"+
    "\7\0\2\225\1\0\1\225\1\0\1\225\1\0\3\225"+
    "\2\0\2\225\3\0\1\225\1\0\2\225\2\0\1\225"+
    "\2\0\2\225\40\0\1\225\7\0\2\226\3\0\1\226"+
    "\2\0\2\226\62\0\1\226\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\5\11\1\277\20\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\7\11\1\300\16\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\7\11\1\301\16\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\10\11"+
    "\1\302\15\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\11\11\1\303\14\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\11\11\1\304\14\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\12\11\1\305\13\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\11\11"+
    "\1\306\14\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\7\11\1\307\16\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\1\310\25\11\25\0\1\11\6\0"+
    "\3\11\1\0\1\11\1\0\1\11\1\0\7\11\3\0"+
    "\11\11\1\311\14\11\25\0\1\11\6\0\3\11\1\0"+
    "\1\11\1\0\1\11\1\0\7\11\3\0\4\11\1\312"+
    "\1\313\20\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\20\11\1\314\5\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\10\11\1\315\15\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\22\11\1\316\3\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\5\11"+
    "\1\317\20\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\11\11\1\320\14\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\5\11\1\321\20\11\25\0\1\11"+
    "\65\0\1\322\33\0\1\265\74\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\10\11\1\323\15\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\7\11\1\324\16\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\13\11\1\325\12\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\1\11"+
    "\1\326\24\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\11\11\1\327\14\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\10\11\1\330\15\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\15\11\1\331\10\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\15\11"+
    "\1\332\10\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\11\11\1\333\14\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\1\334\25\11\25\0\1\11\6\0"+
    "\3\11\1\0\1\11\1\0\1\11\1\0\7\11\3\0"+
    "\11\11\1\335\14\11\25\0\1\11\6\0\3\11\1\0"+
    "\1\11\1\0\1\11\1\0\7\11\3\0\1\336\25\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\13\11\1\337\12\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\7\11\1\340\16\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\11\11"+
    "\1\341\14\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\6\11\1\342\17\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\2\11\1\343\23\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\12\11\1\344\13\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\10\11"+
    "\1\345\15\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\16\11\1\346\7\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\21\11\1\347\4\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\6\11\1\350\17\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\10\11"+
    "\1\351\15\11\25\0\1\11\6\0\3\11\1\0\1\11"+
    "\1\0\1\11\1\0\7\11\3\0\6\11\1\352\17\11"+
    "\25\0\1\11\6\0\3\11\1\0\1\11\1\0\1\11"+
    "\1\0\7\11\3\0\7\11\1\353\16\11\25\0\1\11"+
    "\6\0\3\11\1\0\1\11\1\0\1\11\1\0\7\11"+
    "\3\0\7\11\1\354\16\11\25\0\1\11\6\0\3\11"+
    "\1\0\1\11\1\0\1\11\1\0\7\11\3\0\1\355"+
    "\25\11\25\0\1\11\6\0\3\11\1\0\1\11\1\0"+
    "\1\11\1\0\7\11\3\0\11\11\1\356\14\11\25\0"+
    "\1\11\6\0\3\11\1\0\1\11\1\0\1\11\1\0"+
    "\7\11\3\0\11\11\1\357\14\11\25\0\1\11\6\0"+
    "\3\11\1\0\1\11\1\0\1\11\1\0\7\11\3\0"+
    "\10\11\1\360\15\11\25\0\1\11\6\0\3\11\1\0"+
    "\1\11\1\0\1\11\1\0\7\11\3\0\11\11\1\361"+
    "\14\11\25\0\1\11\6\0\3\11\1\0\1\11\1\0"+
    "\1\11\1\0\7\11\3\0\6\11\1\362\17\11\25\0"+
    "\1\11\6\0\3\11\1\0\1\11\1\0\1\11\1\0"+
    "\7\11\3\0\1\11\1\363\24\11\25\0\1\11\6\0"+
    "\3\11\1\0\1\11\1\0\1\11\1\0\7\11\3\0"+
    "\11\11\1\364\14\11\25\0\1\11\6\0\3\11\1\0"+
    "\1\11\1\0\1\11\1\0\7\11\3\0\11\11\1\365"+
    "\14\11\25\0\1\11\6\0\3\11\1\0\1\11\1\0"+
    "\1\11\1\0\7\11\3\0\10\11\1\366\15\11\25\0"+
    "\1\11\6\0\3\11\1\0\1\11\1\0\1\11\1\0"+
    "\7\11\3\0\2\11\1\367\23\11\25\0\1\11\6\0"+
    "\3\11\1\0\1\11\1\0\1\11\1\0\7\11\3\0"+
    "\7\11\1\370\16\11\25\0\1\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10608];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\10\1\2\11\17\1\7\11\4\1\3\11"+
    "\7\1\2\11\3\1\1\11\3\1\1\11\1\1\1\11"+
    "\1\1\1\0\2\11\1\1\2\0\1\1\3\11\4\0"+
    "\30\1\2\11\1\1\1\11\1\1\10\11\1\0\2\11"+
    "\2\1\11\11\12\1\1\11\1\1\1\11\1\0\1\1"+
    "\1\0\34\1\1\11\1\1\3\11\1\0\1\11\1\0"+
    "\10\11\23\1\1\11\46\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[248];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuilder __string = new StringBuilder();

  public Scanner(String fileName) throws FileNotFoundException {
    __fileName = fileName;
    this.zzReader = new BufferedReader(new FileReader(__fileName));
  }

  public Scanner(String text, boolean unused) {
    __fileName = null;
    this.zzReader = new BufferedReader(new StringReader(text));
  }

  public static Scanner getStringScanner(String text) {
        return new Scanner(text, true);
  }

  private Token getToken(EType code, char c) {
    return getToken(code, Character.toString(c));
  }
  private Token getToken(EType code, String str) {
    return new Token(code, __fileName, yyline+1, yycolumn+1, str);
  }
  private Token getToken(EType code) {
    return getToken(code, yytext());
  }

  private String __fileName = null;



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 204) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return getToken(EType.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Illegal character \""+yytext()+
           "\" at line "+yyline+", column "+yycolumn);
            } 
            // fall through
          case 113: break;
          case 2: 
            { /*nothing*/
            } 
            // fall through
          case 114: break;
          case 3: 
            { return getToken(EType.DIV);
            } 
            // fall through
          case 115: break;
          case 4: 
            { return getToken(EType.MULT);
            } 
            // fall through
          case 116: break;
          case 5: 
            { return getToken(EType.IDENT);
            } 
            // fall through
          case 117: break;
          case 6: 
            { return getToken(EType.INT_LITERAL);
            } 
            // fall through
          case 118: break;
          case 7: 
            { return getToken(EType.DOT);
            } 
            // fall through
          case 119: break;
          case 8: 
            { return getToken(EType.MINUS);
            } 
            // fall through
          case 120: break;
          case 9: 
            { yybegin(CHARLITERAL);
            } 
            // fall through
          case 121: break;
          case 10: 
            { yybegin(STRING); __string.setLength(0);
            } 
            // fall through
          case 122: break;
          case 11: 
            { return getToken(EType.RBRACE);
            } 
            // fall through
          case 123: break;
          case 12: 
            { return getToken(EType.LPAREN);
            } 
            // fall through
          case 124: break;
          case 13: 
            { return getToken(EType.RPAREN);
            } 
            // fall through
          case 125: break;
          case 14: 
            { return getToken(EType.LBRACE);
            } 
            // fall through
          case 126: break;
          case 15: 
            { return getToken(EType.LBRACK);
            } 
            // fall through
          case 127: break;
          case 16: 
            { return getToken(EType.RBRACK);
            } 
            // fall through
          case 128: break;
          case 17: 
            { return getToken(EType.SEMICOLON);
            } 
            // fall through
          case 129: break;
          case 18: 
            { return getToken(EType.COMMA);
            } 
            // fall through
          case 130: break;
          case 19: 
            { return getToken(EType.EQ);
            } 
            // fall through
          case 131: break;
          case 20: 
            { return getToken(EType.GT);
            } 
            // fall through
          case 132: break;
          case 21: 
            { return getToken(EType.LT);
            } 
            // fall through
          case 133: break;
          case 22: 
            { return getToken(EType.NOT);
            } 
            // fall through
          case 134: break;
          case 23: 
            { return getToken(EType.COMP);
            } 
            // fall through
          case 135: break;
          case 24: 
            { return getToken(EType.QUESTION);
            } 
            // fall through
          case 136: break;
          case 25: 
            { return getToken(EType.COLON);
            } 
            // fall through
          case 137: break;
          case 26: 
            { return getToken(EType.AND);
            } 
            // fall through
          case 138: break;
          case 27: 
            { return getToken(EType.OR);
            } 
            // fall through
          case 139: break;
          case 28: 
            { return getToken(EType.PLUS);
            } 
            // fall through
          case 140: break;
          case 29: 
            { return getToken(EType.XOR);
            } 
            // fall through
          case 141: break;
          case 30: 
            { return getToken(EType.MOD);
            } 
            // fall through
          case 142: break;
          case 31: 
            { __string.append( yytext() );
            } 
            // fall through
          case 143: break;
          case 32: 
            { throw new RuntimeException("Unterminated string at end of line");
            } 
            // fall through
          case 144: break;
          case 33: 
            { yybegin(YYINITIAL); 
  			return getToken(EType.STRING_LITERAL, __string.toString());
            } 
            // fall through
          case 145: break;
          case 34: 
            { throw new RuntimeException("Unterminated character literal at end of line");
            } 
            // fall through
          case 146: break;
          case 35: 
            { throw new RuntimeException("Unterminated string at end of regex");
            } 
            // fall through
          case 147: break;
          case 36: 
            { yybegin(YYINITIAL); 
  			return getToken(EType.REGEX_LITERAL, __string.toString());
            } 
            // fall through
          case 148: break;
          case 37: 
            { /*todo: accumulate*/
            } 
            // fall through
          case 149: break;
          case 38: 
            { return getToken(EType.DIVEQ);
            } 
            // fall through
          case 150: break;
          case 39: 
            { return getToken(EType.MULTEQ);
            } 
            // fall through
          case 151: break;
          case 40: 
            { return getToken(EType.FLOAT_LITERAL);
            } 
            // fall through
          case 152: break;
          case 41: 
            { return getToken(EType.DOTDOT);
            } 
            // fall through
          case 153: break;
          case 42: 
            { return getToken(EType.MINUSMINUS);
            } 
            // fall through
          case 154: break;
          case 43: 
            { return getToken(EType.MINUSEQ);
            } 
            // fall through
          case 155: break;
          case 44: 
            { return getToken(EType.K_OR);
            } 
            // fall through
          case 156: break;
          case 45: 
            { return getToken(EType.K_IF);
            } 
            // fall through
          case 157: break;
          case 46: 
            { return getToken(EType.EQEQ);
            } 
            // fall through
          case 158: break;
          case 47: 
            { return getToken(EType.GTEQ);
            } 
            // fall through
          case 159: break;
          case 48: 
            { return getToken(EType.RSHIFT);
            } 
            // fall through
          case 160: break;
          case 49: 
            { return getToken(EType.LTEQ);
            } 
            // fall through
          case 161: break;
          case 50: 
            { return getToken(EType.LSHIFT);
            } 
            // fall through
          case 162: break;
          case 51: 
            { return getToken(EType.NOTEQ);
            } 
            // fall through
          case 163: break;
          case 52: 
            { return getToken(EType.ANDEQ);
            } 
            // fall through
          case 164: break;
          case 53: 
            { return getToken(EType.ANDAND);
            } 
            // fall through
          case 165: break;
          case 54: 
            { return getToken(EType.OREQ);
            } 
            // fall through
          case 166: break;
          case 55: 
            { return getToken(EType.OROR);
            } 
            // fall through
          case 167: break;
          case 56: 
            { return getToken(EType.PLUSEQ);
            } 
            // fall through
          case 168: break;
          case 57: 
            { return getToken(EType.PLUSPLUS);
            } 
            // fall through
          case 169: break;
          case 58: 
            { return getToken(EType.XOREQ);
            } 
            // fall through
          case 170: break;
          case 59: 
            { return getToken(EType.MODEQ);
            } 
            // fall through
          case 171: break;
          case 60: 
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            } 
            // fall through
          case 172: break;
          case 61: 
            { char val = (char) Integer.parseInt(yytext().substring(1),8);
        __string.append( val );
            } 
            // fall through
          case 173: break;
          case 62: 
            { __string.append( '\'' );
            } 
            // fall through
          case 174: break;
          case 63: 
            { __string.append( '\"' );
            } 
            // fall through
          case 175: break;
          case 64: 
            { __string.append( '\\' );
            } 
            // fall through
          case 176: break;
          case 65: 
            { __string.append( '\n' );
            } 
            // fall through
          case 177: break;
          case 66: 
            { __string.append( '\b' );
            } 
            // fall through
          case 178: break;
          case 67: 
            { __string.append( '\t' );
            } 
            // fall through
          case 179: break;
          case 68: 
            { __string.append( '\f' );
            } 
            // fall through
          case 180: break;
          case 69: 
            { __string.append( '\r' );
            } 
            // fall through
          case 181: break;
          case 70: 
            { yybegin(YYINITIAL); 
		return getToken(EType.CHARACTER_LITERAL, yytext().charAt(0));
            } 
            // fall through
          case 182: break;
          case 71: 
            { __string.append( '}' );
            } 
            // fall through
          case 183: break;
          case 72: 
            { return getToken(EType.BASED_LITERAL);
            } 
            // fall through
          case 184: break;
          case 73: 
            { return getToken(EType.K_AND);
            } 
            // fall through
          case 185: break;
          case 74: 
            { return getToken(EType.K_NOT);
            } 
            // fall through
          case 186: break;
          case 75: 
            { return getToken(EType.K_NIL);
            } 
            // fall through
          case 187: break;
          case 76: 
            { return getToken(EType.K_DEF);
            } 
            // fall through
          case 188: break;
          case 77: 
            { return getToken(EType.K_FOR);
            } 
            // fall through
          case 189: break;
          case 78: 
            { return getToken(EType.K_INT);
            } 
            // fall through
          case 190: break;
          case 79: 
            { return getToken(EType.K_VAR);
            } 
            // fall through
          case 191: break;
          case 80: 
            { return getToken(EType.RSHIFTEQ);
            } 
            // fall through
          case 192: break;
          case 81: 
            { return getToken(EType.URSHIFT);
            } 
            // fall through
          case 193: break;
          case 82: 
            { return getToken(EType.LSHIFTEQ);
            } 
            // fall through
          case 194: break;
          case 83: 
            { yybegin(REGEX); __string.setLength(0);
            } 
            // fall through
          case 195: break;
          case 84: 
            { yybegin(YYINITIAL); 
	    int val = Integer.parseInt(yytext().substring(1,yylength()-1),8);
	    return getToken(EType.CHARACTER_LITERAL, (char)val);
            } 
            // fall through
          case 196: break;
          case 85: 
            { yybegin(YYINITIAL); return getToken(EType.CHARACTER_LITERAL, '\'');
            } 
            // fall through
          case 197: break;
          case 86: 
            { yybegin(YYINITIAL); return getToken(EType.CHARACTER_LITERAL, '\"');
            } 
            // fall through
          case 198: break;
          case 87: 
            { yybegin(YYINITIAL); return getToken(EType.CHARACTER_LITERAL, '\\');
            } 
            // fall through
          case 199: break;
          case 88: 
            { yybegin(YYINITIAL); return getToken(EType.CHARACTER_LITERAL, '\n');
            } 
            // fall through
          case 200: break;
          case 89: 
            { yybegin(YYINITIAL); return getToken(EType.CHARACTER_LITERAL, '\b');
            } 
            // fall through
          case 201: break;
          case 90: 
            { yybegin(YYINITIAL); return getToken(EType.CHARACTER_LITERAL, '\t');
            } 
            // fall through
          case 202: break;
          case 91: 
            { yybegin(YYINITIAL); return getToken(EType.CHARACTER_LITERAL, '\f');
            } 
            // fall through
          case 203: break;
          case 92: 
            { yybegin(YYINITIAL); return getToken(EType.CHARACTER_LITERAL, '\r');
            } 
            // fall through
          case 204: break;
          case 93: 
            { return getToken(EType.K_BOOL);
            } 
            // fall through
          case 205: break;
          case 94: 
            { return getToken(EType.K_TRUE);
            } 
            // fall through
          case 206: break;
          case 95: 
            { return getToken(EType.K_ELSE);
            } 
            // fall through
          case 207: break;
          case 96: 
            { return getToken(EType.K_ELIF);
            } 
            // fall through
          case 208: break;
          case 97: 
            { return getToken(EType.URSHIFTEQ);
            } 
            // fall through
          case 209: break;
          case 98: 
            { return getToken(EType.K_CONST);
            } 
            // fall through
          case 210: break;
          case 99: 
            { return getToken(EType.K_CLASS);
            } 
            // fall through
          case 211: break;
          case 100: 
            { return getToken(EType.K_FALSE);
            } 
            // fall through
          case 212: break;
          case 101: 
            { return getToken(EType.K_FLOAT);
            } 
            // fall through
          case 213: break;
          case 102: 
            { return getToken(EType.K_WHILE);
            } 
            // fall through
          case 214: break;
          case 103: 
            { return getToken(EType.K_STATIC);
            } 
            // fall through
          case 215: break;
          case 104: 
            { return getToken(EType.K_IMPORT);
            } 
            // fall through
          case 216: break;
          case 105: 
            { return getToken(EType.K_PUBLIC);
            } 
            // fall through
          case 217: break;
          case 106: 
            { return getToken(EType.K_UNLESS);
            } 
            // fall through
          case 218: break;
          case 107: 
            { return getToken(EType.K_EXTENDS);
            } 
            // fall through
          case 219: break;
          case 108: 
            { return getToken(EType.K_PACKAGE);
            } 
            // fall through
          case 220: break;
          case 109: 
            { return getToken(EType.K_PRIVATE);
            } 
            // fall through
          case 221: break;
          case 110: 
            { return getToken(EType.K_INTERFACE);
            } 
            // fall through
          case 222: break;
          case 111: 
            { return getToken(EType.K_PROTECTED);
            } 
            // fall through
          case 223: break;
          case 112: 
            { return getToken(EType.K_IMPLEMENTS);
            } 
            // fall through
          case 224: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
